version: '3.8'

services:
  backend:
    image: tiuzaodagoiaba/backmensal:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    driver: bridge