name: Testes Automatizados Java

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Compilar e rodar testes
        run: mvn clean test
        env:
          SPRING_PROFILES_ACTIVE: test
